require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'navigation2' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # permissions_path = '../node_modules/react-native-permissions/ios'
  # pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera.podspec"
# react-native-permissions permission handlers
permissions_path = '../node_modules/react-native-permissions/ios'

pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-restart', :path => '../node_modules/react-native-restart'

  target 'navigation2Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'navigation2-tvOS' do
  # Pods for navigation2-tvOS

  target 'navigation2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
